#ifndef R_RESOURCES_H
#define R_RESOURCES_H 1

#include "D_Common.h"

extern int MAP_SHAPE[MAP_WIDTH * MAP_HEIGHT];

extern int SHAPE_T[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT];       
extern int SHAPE_L_LEFT[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT];  
extern int SHAPE_L_RIGHT[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT]; 
extern int SHAPE_Z_LEFT[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT];  
extern int SHAPE_Z_RIGHT[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT]; 
extern int SHAPE_BLOCK[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT];   
extern int SHAPE_STICK[COUNT_DIRECTIONS][PIECE_WIDTH * PIECE_HEIGHT];   

#endif
